---
title: "Exciting wet/dry synthetic biology PhD opportunity with industrial links"
output: html_document
---

A very exciting 4-year PhD opportunity has arisen for a capable student to work in the Wilson/Sudbery labs at the University of Sheffield together with a **world leading biologics R&D company**, on a project encompassing **synthetic biology, gene expression and computational biology**.  Students will gain experience working with the **latest molecular biology and computational techniques**, knowing that they are applying novel basic biology to science with an immediate **real-world impact**. The successful student will also gain experience working with an industrial partner, **invaluable for those seeking a career in industry**, but also attractive for those wishing to follow a more academic path.

 The PhD is a 4-year EPSRC studentship, **fully funded for the whole four years**, both in terms of stipend for the student and resources to carry out the project. In addition, it will include the opportunity for the chosen student to travel to our partner's campus, as well as the possibility of attending international scientific meetings. 
 
 The PhD is open to any student with a “connection” to the UK, usually citizenship or residence, with or expecting at least a 2.1 in a relevant Bachelor or Master’s degree (including, but not limited to a Biology or Computing subject). You should have **some experience in either wet-lab biology or computation**. Experience in both is desirable, but not necessary. However, a drive to master both is essential. 
 
 If you are interested, let us know by sending a CV to Ian Sudbery (i.sudbery@sheffield.ac.uk) or Stuart Wilson (stuart.wilson@sheffield.ac.uk) no later than **midday Thursday 8th of June**.